namespace: osac
name: config_as_code
version: 1.0.0
readme: README.md
authors:
- Adrien Gentil @adriengentil
description: OSAC's AAP configuration as code
license:
- Apache-2.0
tags:
  - infrastructure
repository: https://github.com/osac-project/osac
issues: https://github.com/osac-project/osac/issues
build_ignore: []
dependencies:
  ansible.platform: "2.5.20250326"
  ansible.hub: "1.0.0"
  ansible.controller: "4.6.11"
  infra.aap_configuration: "3.4.1"
