apiVersion: v2
name: bare-metal-fulfillment-operator
description: Bare Metal Fulfillment Operator - manages bare metal custom resources
type: application
version: 0.0.11-nightly.20260912.e38c7ab.30.1
appVersion: 0.0.11-nightly.20260912.e38c7ab.30.1
