fullnameOverride: "bmf-operator"
image:
  repository: ghcr.io/osac-project/bare-metal-fulfillment-operator
  tag: sha-e38c7ab # PLACEHOLDER -- overwritten at release time by publish-charts.yaml
  pullPolicy: Always
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
serviceAccount:
  create: true
  name: ""
secrets:
  inventoryConfig: "osac-inventory-config"
  managementConfig: "osac-management-config"
  osClouds: "osac-os-clouds"
  bcmCerts: "osac-bcm-certs"
configMaps:
  profiles: "osac-profiles"
env:
  aapUrl: ""
  aapTokenSecretName: "osac-aap-api-token"
  aapTokenSecretKey: "token"
  aapInsecureSkipVerify: ""
  enableNetworkingProvisioning: "false"
bcm:
  enabled: false
  url: ""
  cert: ""
  key: ""
  caCert: ""
  insecureSkipVerify: false
  hostClass: "bcm"
  bmhNamespace: ""
metal3:
  enabled: false
  namespace: ""
  hostClass: "metal3"
