apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.11-nightly.20260925.e38c7ab.43.1
appVersion: 0.0.11-nightly.20260925.e38c7ab.43.1
