apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.11-nightly.20260927.e38c7ab.45.1
appVersion: 0.0.11-nightly.20260927.e38c7ab.45.1
