apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260926.e38c7ab.44.1
appVersion: 0.0.13-nightly.20260926.e38c7ab.44.1
