apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260912.e38c7ab.30.1
appVersion: 0.0.13-nightly.20260912.e38c7ab.30.1
