apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260927.e38c7ab.45.1
appVersion: 0.0.13-nightly.20260927.e38c7ab.45.1
