apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.12-nightly.20260923.e38c7ab.41.1
appVersion: 0.0.12-nightly.20260923.e38c7ab.41.1
